ln -s -f $(cd `dirname $0`; pwd)/oh_my_zsh/.zshrc ~
ln -s -f $(cd `dirname $0`; pwd)/rime/Library/Rime/default.custom.yaml ~/Library/Rime
ln -s -f $(cd `dirname $0`; pwd)/rime/Library/Rime/double_pinyin_flypy.custom.yaml ~/Library/Rime
ln -s -f $(cd `dirname $0`; pwd)/ss/.ShadowsocksX ~
ln -s -f $(cd `dirname $0`; pwd)/vim/.vimrc ~
Ln -s -f $(cd `dirname $0`; pwd)/vim/.vim/.vimrc.custom ~/.vim
ln -s -f $(cd `dirname $0`; pwd)/vim/.vim/.vimrc.coding ~/.vim
ln -s -f $(cd `dirname $0`; pwd)/vim/.vim/.vimrc.bundles ~/.vim
ln -s -f $(cd `dirname $0`; pwd)/vim/.ackrc ~
ln -s -f $(cd `dirname $0`; pwd)/nvim ~/.config
